server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-config-source: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**, /auth/**

        - id: alumno-service
          uri: lb://ALUMNO-SERVICE
          predicates:
            - Path=/alumnos/**

        - id: curso-service
          uri: lb://CURSO-SERVICE
          predicates:
            - Path=/cursos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/